name: Generates Docker Image Conductor

on:
  push:
    branches: [main]
    paths:
      - conductor/**/Dockerfile*
      - build-settings.yml
      - baker.py

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  OWNER: ${{ github.repository_owner }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.OWNER }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Python deps
        run: pipx run pip install pyyaml

      - name: Build & Push (nur wenn nötig)
        run: |
          cd conductor && python baker.py build \
            --settings build-settings.yml \
            --targets srv-sqlite
